### ISSUE TITLE
pipdeptree --freeze fails with AttributeError exception (no attribute 'editable')

### ISSUE THREAD

**Issue by phries** [naiquevin/pipdeptree#150]
Hello! I came across this error in my typical usage pattern, where `--freeze` is now failing. Maybe the internal pip API changed?

Console output:
```
$ python3 -m pipdeptree --freeze
Warning!!! Possibly conflicting dependencies found:
* launchpadlib==1.10.6
 - testresources [required: Any, installed: ?]
------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pipdeptree.py", line 878, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pipdeptree.py", line 872, in main
    render_text(tree, args.all, args.freeze)
  File "/usr/local/lib/python3.6/dist-packages/pipdeptree.py", line 510, in render_text
    lines = flatten([aux(p) for p in nodes])
  File "/usr/local/lib/python3.6/dist-packages/pipdeptree.py", line 510, in <listcomp>
    lines = flatten([aux(p) for p in nodes])
  File "/usr/local/lib/python3.6/dist-packages/pipdeptree.py", line 498, in aux
    node_str = node.render(parent, frozen)
  File "/usr/local/lib/python3.6/dist-packages/pipdeptree.py", line 107, in render
    return self.render_as_root(frozen)
  File "/usr/local/lib/python3.6/dist-packages/pipdeptree.py", line 141, in render_as_root
    return self.__class__.frozen_repr(self._obj)
  File "/usr/local/lib/python3.6/dist-packages/pipdeptree.py", line 113, in frozen_repr
    fr = frozen_req_from_dist(obj)
  File "/usr/local/lib/python3.6/dist-packages/pipdeptree.py", line 81, in frozen_req_from_dist
    return FrozenRequirement.from_dist(dist)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/freeze.py", line 257, in from_dist
    req, editable, comments = _get_editable_info(dist)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/freeze.py", line 165, in _get_editable_info
    if not dist.editable:
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2816, in __getattr__
    return getattr(self._provider, attr)
AttributeError: 'PathMetadata' object has no attribute 'editable'
```

Versions:
Lubuntu 18.04.5 (and separate system on Ubuntu 18.04.5)
Python 3.6.9
pip 21.2.1 
pipdeptree 2.0.0

In case it is needed, here is how to get there from a fresh system:
```
sudo apt-get install python3-pip
sudo pip3 install --upgrade pip
sudo pip3 install --upgrade virtualenv pipdeptree
pip3 install --user numpy # or more or less any package
python3 -m pipdeptree --freeze # error output above
```

**Comment by liezl-scio** [comment]
Having this problem too

```
  File "/home/liezl/.local/lib/python3.7/site-packages/pipdeptree.py", line 
510, in <listcomp>
    lines = flatten([aux(p) for p in nodes])
  File "/home/liezl/.local/lib/python3.7/site-packages/pipdeptree.py", line 
498, in aux
    node_str = node.render(parent, frozen)
  File "/home/liezl/.local/lib/python3.7/site-packages/pipdeptree.py", line 
107, in render
    return self.render_as_root(frozen)
  File "/home/liezl/.local/lib/python3.7/site-packages/pipdeptree.py", line 
141, in render_as_root
    return self.__class__.frozen_repr(self._obj)
  File "/home/liezl/.local/lib/python3.7/site-packages/pipdeptree.py", line 
113, in frozen_repr
    fr = frozen_req_from_dist(obj)
  File "/home/liezl/.local/lib/python3.7/site-packages/pipdeptree.py", line 
81, in frozen_req_from_dist
    return FrozenRequirement.from_dist(dist)
  File "/home/liezl/.local/lib/python3.7/site-packages/pip/_internal/operati
ons/freeze.py", line 257, in from_dist
    req, editable, comments = _get_editable_info(dist)
  File "/home/liezl/.local/lib/python3.7/site-packages/pip/_internal/operati
ons/freeze.py", line 165, in _get_editable_info
    if not dist.editable:
  File "/home/liezl/.local/lib/python3.7/site-packages/pip/_vendor/pkg_resou
rces/__init__.py", line 2816, in __getattr__
    return getattr(self._provider, attr)
AttributeError: 'FileMetadata' object has no attribute 'editable'
```

**Comment by liezl-scio** [comment]
Running just `pipdeptree` works fine though

**Comment by naiquevin** [comment]
Thanks for reporting. Yes, it's because pip's internal API change. I've identified the fix, will push it shortly.

**Comment by naiquevin** [comment]
Released version 2.1.0 to PyPI - https://pypi.org/project/pipdeptree/2.1.0/
