### ISSUE TITLE
Odd error on appveyor when calling pipdeptree

### ISSUE THREAD

**Issue by xoviat** [naiquevin/pipdeptree#75]
The full test is [here](https://ci.appveyor.com/project/xoviat/pyinstaller-utils/build/1.0.151/job/9cd3576e8x8jdtw3), and the traceback is below:

```
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "c:\python35\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "c:\python35\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "c:\python35\lib\site-packages\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "c:\python35\lib\site-packages\pip\vcs\subversion.py", line 9, in <module>
    from pip.index import Link
  File "c:\python35\lib\site-packages\pip\index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "c:\python35\lib\site-packages\pip\wheel.py", line 6, in <module>
    import compileall
  File "c:\python35\lib\compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "c:\python35\lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "c:\python35\lib\site-packages\concurrent\futures\_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
c:\python35\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\pipdeptree.exe\__main__.py", line 5, in <module>
  File "c:\python35\lib\site-packages\pipdeptree.py", line 16, in <module>
    import pip
  File "c:\python35\lib\site-packages\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "c:\python35\lib\site-packages\pip\vcs\subversion.py", line 9, in <module>
    from pip.index import Link
  File "c:\python35\lib\site-packages\pip\index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "c:\python35\lib\site-packages\pip\wheel.py", line 6, in <module>
    import compileall
  File "c:\python35\lib\compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "c:\python35\lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "c:\python35\lib\site-packages\concurrent\futures\_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid synta
```

I'm not exactly sure what is going on, but an exception handler may need to be implemented.

**Comment by xoviat** [comment]
I don't believe now that this is related to pipdeptree.
